docs/DeveloperGuide.md
=> Update DG with target user profile, value proposition, and user stories

.github/workflows/gradle.yml
=> Fix Java CI workflow

docs/_config.yml, docs/_sass/minima/_base.scss
=> Update Jekyll site settings

docs/DeveloperGuide.md
=> Update DG with use cases

docs/DeveloperGuide.md
=> Update DG with glossary

README.md, docs/_config.yml
=> Update README.md contents

config/checkstyle/checkstyle.xml
Updates the checkstyle rules in `checkstyle.xml` to more closely match those found in the SE-EDU style guidelines.
=> Update checkstyle rules

src/main/resources/view/MainWindow.fxml
=> Update window title to INcontact

docs/UserGuide.md
=> Fix commands in UserGuide.md

src/main/java/seedu/address/logic/commands/AddTagToRelationshipCommand.java, src/main/java/seedu/address/logic/commands/DeleteTagFromRelationshipCommand.java, src/main/java/seedu/address/logic/parser/AddTagToRelationshipCommandParser.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/logic/parser/DeleteTagFromRelationshipCommandParser.java, src/main/java/seedu/address/model/AddressBook.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/relationship/Relationship.java, src/main/java/seedu/address/model/relationship/UniqueRelationshipList.java, src/test/java/seedu/address/logic/commands/AddCommandTest.java, src/test/java/seedu/address/testutil/ModelStub.java
Tests need to be updated later.
Fixes #95.
=> Allow adding and removing tags from existing relationships

src/main/java/seedu/address/logic/commands/AddRelationshipCommand.java, src/main/java/seedu/address/logic/commands/DeleteRelationshipCommand.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/ui/PersonListPanel.java, src/test/java/seedu/address/logic/commands/AddCommandTest.java, src/test/java/seedu/address/model/ModelManagerTest.java, src/test/java/seedu/address/testutil/ModelStub.java
=> 124 refresh gui on relationship add

src/main/java/seedu/address/logic/Messages.java, src/main/java/seedu/address/model/event/Event.java, src/main/java/seedu/address/model/relationship/UniqueRelationshipList.java, src/test/java/seedu/address/logic/commands/AddEventCommandTest.java, src/test/java/seedu/address/model/AddressBookTest.java
=> Add extra tests

src/main/java/seedu/address/logic/commands/AddTagToRelationshipCommand.java, src/main/java/seedu/address/logic/commands/DeleteTagFromRelationshipCommand.java
=> Add extra help text to relationship tag command strings

src/main/java/seedu/address/MainApp.java, src/main/java/seedu/address/logic/commands/SortCommand.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/logic/parser/FindTagCommandParser.java, src/main/java/seedu/address/logic/parser/SortCommandParser.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/test/java/seedu/address/logic/commands/AddCommandTest.java, src/test/java/seedu/address/logic/parser/FindNameCommandParserTest.java, src/test/java/seedu/address/testutil/ModelStub.java
=> Build for release

docs/diagrams/SortSequenceDiagram.puml, src/main/java/seedu/address/logic/LogicManager.java, src/main/java/seedu/address/logic/commands/SortCommand.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/logic/parser/FindRelationshipCommandParser.java, src/main/java/seedu/address/logic/parser/SortCommandParser.java, src/main/java/seedu/address/model/AddressBook.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/list/SortedFilteredList.java, src/main/java/seedu/address/model/person/UniquePersonList.java, src/main/java/seedu/address/model/predicate/RelationshipContainsKeywordsAsSubstringPredicate.java, src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
=> 139 update uml sort sequence

build.gradle, src/main/java/seedu/address/logic/commands/AddEventCommand.java, src/main/java/seedu/address/logic/parser/AddEventCommandParser.java, src/main/java/seedu/address/logic/parser/DateParserUtil.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/model/event/Event.java, src/main/java/seedu/address/storage/JsonAdaptedEvent.java, src/test/java/seedu/address/logic/commands/AddEventCommandTest.java
=> Use natural language for date parsing

docs/DeveloperGuide.md, docs/UserGuide.md
=> Update DG description related to add

src/main/java/seedu/address/ui/HelpWindow.java, src/main/java/seedu/address/ui/MainWindow.java, src/main/java/seedu/address/ui/PersonCard.java, src/main/resources/view/MainWindow.fxml, src/main/resources/view/PersonListCard.fxml
=> Improve on GUI

src/main/resources/view/MainWindow.fxml
=> Fix content not filling window

src/main/java/seedu/address/logic/commands/AddRelationshipCommand.java, src/main/java/seedu/address/logic/commands/DeleteRelationshipCommand.java, src/main/java/seedu/address/logic/parser/AddRelationshipCommandParser.java, src/main/java/seedu/address/logic/parser/DeleteRelationshipCommandParser.java, src/main/java/seedu/address/model/AddressBook.java, src/main/java/seedu/address/model/predicate/RelationshipContainsKeywordsAsSubstringPredicate.java, src/main/java/seedu/address/model/relationship/Relationship.java, src/main/java/seedu/address/model/relationship/UniqueRelationshipList.java, src/main/java/seedu/address/model/relationship/exceptions/DuplicateRelationshipException.java, src/main/java/seedu/address/model/relationship/exceptions/RelationshipNotFoundException.java, src/main/java/seedu/address/storage/JsonAdaptedRelationship.java, src/main/java/seedu/address/ui/PersonCard.java, src/main/java/seedu/address/ui/PersonListPanel.java, src/test/java/seedu/address/logic/commands/AddRelationshipCommandTest.java, src/test/java/seedu/address/logic/commands/DeleteRelationshipCommandTest.java, src/test/java/seedu/address/logic/parser/DeleteRelationshipCommandParserTest.java, src/test/java/seedu/address/model/relationship/RelationshipTest.java, src/test/java/seedu/address/testutil/RelationshipBuilder.java
=> Improve code quality for Relationships

docs/diagrams/RedoListSequenceDiagram.puml, docs/diagrams/RedoSequenceDiagram.puml
=> Add redoList sequence diagram and redo sequence diagram

docs/DeveloperGuide.md
=> Fix DG table of contents

docs/UserGuide.md
=> Update user guide quick start

docs/DevOps.md, docs/SettingUp.md, docs/UserGuide.md, docs/index.md
=> Rename AddressBook to INcontact

src/main/resources/view/MainWindow.fxml
=> Update UI design

src/main/java/seedu/address/logic/parser/AddCommandParser.java, src/main/java/seedu/address/model/person/Address.java, src/main/java/seedu/address/model/person/Email.java, src/main/java/seedu/address/model/person/Phone.java, src/main/java/seedu/address/storage/JsonAdaptedPerson.java
=> Update add parser

src/main/java/seedu/address/MainApp.java, src/main/java/seedu/address/model/person/Address.java, src/test/java/seedu/address/model/person/AddressTest.java, src/test/java/seedu/address/model/person/EmailTest.java, src/test/java/seedu/address/model/person/PhoneTest.java
=> Add tests for add

src/main/java/seedu/address/model/AddressBook.java, src/main/java/seedu/address/model/person/Person.java, src/main/java/seedu/address/model/relationship/UniqueRelationshipList.java, src/main/java/seedu/address/storage/JsonAdaptedPerson.java, src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
Fixes #228 
Fixes #245 
Fixes #261 
Fixes #292
=> Handle relationship GUI bugs

docs/UserGuide.md, docs/team/trknguyen.md
=> Update UG add ppp

src/main/java/seedu/address/logic/commands/DeleteRelationshipCommand.java, src/test/java/seedu/address/logic/commands/DeleteRelationshipCommandTest.java
=> Modify relationship delete messages

src/main/java/seedu/address/MainApp.java
=> Save data during application shutdown

docs/UserGuide.md
=> Update relevant UG documentations

src/main/java/seedu/address/logic/commands/AddTagToRelationshipCommand.java, src/test/java/seedu/address/logic/LogicManagerTest.java, src/test/java/seedu/address/logic/commands/AddRelationshipCommandTest.java, src/test/java/seedu/address/logic/commands/AddTagToRelationshipCommandTest.java, src/test/java/seedu/address/logic/commands/DeleteRelationshipCommandTest.java, src/test/java/seedu/address/logic/commands/DeleteTagFromRelationshipCommandTest.java, src/test/java/seedu/address/logic/parser/AddRelationshipCommandParserTest.java, src/test/java/seedu/address/logic/parser/AddTagToRelationshipCommandParserTest.java, src/test/java/seedu/address/logic/parser/AddressBookParserTest.java, src/test/java/seedu/address/logic/parser/DeleteTagFromRelationshipCommandParserTest.java, src/test/java/seedu/address/model/AddressBookTest.java, src/test/java/seedu/address/model/ModelManagerTest.java, src/test/java/seedu/address/model/relationship/RelationshipTest.java, src/test/java/seedu/address/model/relationship/UniqueRelationshipListTest.java, src/test/java/seedu/address/model/relationship/exceptions/DuplicateRelationshipExceptionTest.java, src/test/java/seedu/address/storage/JsonAdaptedRelationshipTest.java, src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java, src/test/java/seedu/address/testutil/TypicalEvents.java, src/test/java/seedu/address/testutil/TypicalRelationships.java
=> 229 more relationship tests
